version: "3"
services:
  web:
    # The image is built locally from the     
    #current directory and deplopyed as image
    build: .     
    ports:
      - "8090:8080"
    networks:
      - webnet
networks:
  webnet:

##Use docker-compose up to run without stack and deploy options