version: '3'
services:
  web:     
    image: pbadhe34/my-apps:app1 
    ports:
      - "8090"    
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
   
  redis:
    image: "redis" 
    volumes:
      - "/home/docker/data:/data"      
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure